version: "3"
services:   
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"  # InfluxDB HTTP API
      - "8089:8089/udp"  # InfluxDB UDP
    environment:
      - INFLUXDB_DB=
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - ./influxdb-data:/var/lib/influxdb

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - "8888:8888"  # Chronograf web UI
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086  # Use the service name defined in the Docker Compose file
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=password
      - INFLUXDB_NAME=mydb
